global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK'

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'pager-duty-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-notifications'
      continue: true
    - match:
        service: tournament-management
      receiver: 'email-admin'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true
        icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
        icon_emoji: ':warning:'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ template "slack.grafana" . }}'

  - name: 'pager-duty-critical'
    pagerduty_configs:
      - routing_key: 'YOUR_PAGERDUTY_KEY'
        description: '{{ template "pagerduty.description" . }}'
        severity: '{{ if eq .GroupLabels.severity "critical" }}critical{{ else }}warning{{ end }}'
        client: 'Tournament Management'
        client_url: '{{ template "pagerduty.clientURL" . }}'

  - name: 'email-admin'
    email_configs:
      - to: 'admin@tournament.com'
        from: 'alertmanager@tournament.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'alertmanager@tournament.com'
        auth_password: 'YOUR_EMAIL_PASSWORD'
        headers:
          subject: 'Tournament Management Alert: {{ .GroupLabels.alertname }}'
        html: '{{ template "email.html" . }}'

templates:
  - '/etc/alertmanager/template/*.tmpl'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service'] 