apiVersion: v1
kind: Secret
metadata:
  name: tournament-secrets
  namespace: tournament
  labels:
    app: tournament-management
type: Opaque
data:
  # Base de datos PostgreSQL
  database-url: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZToyNDMyL3RvdXJuYW1lbnRfcHJvZA==
  database-username: dG91cm5hbWVudF91c2Vy
  database-password: dG91cm5hbWVudF9wYXNz
  
  # Redis
  redis-password: cmVkaXNfcGFzc3dvcmQ=
  
  # RabbitMQ
  rabbitmq-username: dG91cm5hbWVudF91c2Vy
  rabbitmq-password: dG91cm5hbWVudF9wYXNz
  
  # JWT Secret (debe ser cambiado en producción)
  jwt-secret: dG91cm5hbWVudF9qd3Rfc2VjcmV0X2Zvcl9kZXZlbG9wbWVudF9vbmx5
  
  # API Keys (ejemplo)
  twitch-api-key: dHdpdGNoX2FwaV9rZXlfZXhhbXBsZQ==
  youtube-api-key: eW91dHViZV9hcGlfa2V5X2V4YW1wbGU=
  
  # Certificados SSL (ejemplo)
  ssl-cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==
  ssl-key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCg== 